### ISSUE TITLE
Guard against balance overflow and underflow

### ISSUE THREAD

**Issue by hai-rise** [risechain/pevm#311]
Should use `saturating_add` and `saturating_sub` by default, and raise errors where needed.

**Comment by varun-doshi** [comment]
I'd like to take this up

**Comment by hai-rise** [comment]
@thecactusblue Have you started on this one 🙏 ?

**Comment by hai-rise** [comment]
@varun-doshi this one is available, can I assign you now :pray:?

**Comment by varun-doshi** [comment]
Yes please

**Comment by varun-doshi** [comment]
Acknowledged
