### ISSUE TITLE
Support EOF

### ISSUE THREAD

**Issue by hai-rise** [risechain/pevm#316]
https://github.com/risechain/pevm/blob/24266be8d317bdcbe8f8ac10c6ce34ae7298802d/src/storage.rs#L104

**Comment by hai-rise** [comment]
@byhashdong Not yet, but it's currently blocked by #358. I'll ping you when this is ready :pray:.

**Comment by byhashdong** [comment]
OK, Thanks a lot!

**Comment by hai-rise** [comment]
@byhashdong This is unblocked now :pray:.

**Comment by byhashdong** [comment]
@hai-rise I will take it.

**Comment by hai-rise** [comment]
@byhashdong Thank you!!

**Comment by byhashdong** [comment]
@hai-rise Can you help clarify why do we introduce the `EVMCode` struct, but not reuse `ByteCode` from `revm`?

**Comment by hai-rise** [comment]
@byhashdong This was a hard decision but `revm` types weren't optimal for `pevm`. We need to make a fork to make it easier to implement `pevm` and optimize several hot paths. Eventually, we decided on our types (`EvmCode` included) for:
- Moving `code` and `code_hash` out of `AccountBasic` (counterpart of `AccountInfo`) so we don't need to duplicate codes in the MV memory.
- Add more features like `Storage::code_hash` and `Storage::has_storage`.
- Do not persist extra data like the `raw` bytecode in `Bytecode::Eip7702`.
- (TODO) Do not duplicate bytecodes in EVM state transitions.
- (TODO) Make more key types like `Evm` thread-safe, to be pooled and shared among worker threads instead of expensive construction per transaction execution.
- Improve compatibility so library users don't need to use our forked `revm` (with the cost of some runtime type conversions).
 
For state-of-the-art performance, we'll likely need to:
- Rewrite large portions of `revm` (so cannot upstream everything), or 
- Switch to a more performant EVM executor like `evmone` or JIT/AOH compiler, or 
- Inline our EVM implementation specifically designed for parallel execution (thread-safe types and states, more native caches and instrumentation, etc.).  

And library users will only use `pevm` and `alloy` types to interface (for minimal conversions).

Nevertheless, we still provide a branch that uses `revm` instead of our custom types for integration with existing `revm` users like upstream Reth: https://github.com/risechain/pevm/pull/360/files.

**Comment by byhashdong** [comment]
Nice, Thanks for you clear explain @hai-rise

**Comment by byhashdong** [comment]
@hai-rise just submitted pr(#374), please feel free to have a review, thanks!

**Comment by hai-rise** [comment]
Done in #374.

**Comment by byhashdong** [comment]
> Done in #374. 

Thanks for your precise review.
