### ISSUE TITLE
Support EIP-7702

### ISSUE THREAD

**Issue by hai-rise** [risechain/pevm#317]
https://github.com/risechain/pevm/blob/24266be8d317bdcbe8f8ac10c6ce34ae7298802d/src/storage.rs#L105

**Comment by EdwardJES** [comment]
Hey @hai-rise, getting Pectra supported is exciting. How do you expect the `EvmCode` struct to evolve here? If this is expected to hold all bytecode formats, I think the best path forward would be adopting a similar API to how revm did it: https://github.com/bluealloy/revm/blob/acf1a70ca8350e5144275769262f59a66700a49d/crates/primitives/src/bytecode.rs#L19. 

We would then have individual structs per bytecode where we can extend the types. 

Did you have a similar pattern in mind?

Ty.

**Comment by hai-rise** [comment]
> Hey @hai-rise, getting Pectra supported is exciting. How do you expect the `EvmCode` struct to evolve here? If this is expected to hold all bytecode formats, I think the best path forward would be adopting a similar API to how revm did it: https://github.com/bluealloy/revm/blob/acf1a70ca8350e5144275769262f59a66700a49d/crates/primitives/src/bytecode.rs#L19.
> 
> We would then have individual structs per bytecode where we can extend the types.
> 
> Did you have a similar pattern in mind?
> 
> Ty.

Yes, and #358 is in the right direction already!

**Comment by hai-rise** [comment]
Done in #358.
