### ISSUE TITLE
`data`: better binary formats to save disk

### ISSUE THREAD

**Issue by hai-rise** [risechain/pevm#322]
GitHub is already complaining about `data/bytecodes.bincode` being over 50MB.

**Comment by byhashdong** [comment]
How about writing compressed bincode?

**Comment by hai-rise** [comment]
@byhashdong I don't have a strong preference here, but adding a dev dependency to (de)compress `data/bytecodes.bincode` does sound like a good step 🙏.

**Comment by byhashdong** [comment]
OK, I will take this one.

**Comment by hai-rise** [comment]
@byhashdong That would be awesome, thank you!

**Comment by byhashdong** [comment]
@hai-rise I have already submitted the PR(#365), Can you help have a review? Thanks!

**Comment by hai-rise** [comment]
Done for now.
