### ISSUE TITLE
Report test name that fails to parse sender address

### ISSUE THREAD

**Issue by hai-rise** [risechain/pevm#326]
https://github.com/risechain/pevm/blob/24266be8d317bdcbe8f8ac10c6ce34ae7298802d/tests/ethereum/main.rs#L71

**Comment by varun-doshi** [comment]
Is it an acceptable solution if the function signature is changed from:
```
fn run_test_unit(path: &Path, unit: TestUnit) {
```

To
```
fn run_test_unit(path: &Path, unit: TestUnit, test_name:String) {
```

**Comment by hai-rise** [comment]
@varun-doshi I think we can just report the `path`, which is more searchable too :pray:.

**Comment by varun-doshi** [comment]
Understood
So then passing the `path` variable to `build_tx_env` should work(?)

I'd like to take this up

**Comment by hai-rise** [comment]
@varun-doshi That should work, thank you!
